name: Sphinx Documentation
on:
  # runs with manual start from Actions tab
  workflow_dispatch:
  # runs on pushes
  push:
    branches: [  main, develop ]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
        ref: ${{ github.ref }}

    - name: Set up Python 3.
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: install
      run:  pip install sphinx sphinx-rtd-theme sphinx-copybutton 

    - name: Build documentation.
      run: |
          ## Init the target folder. 
          # We will put all site documentation there.
          mkdir -p gh-pages
          touch gh-pages/.nojekyll

          git checkout main
          git fetch
          git pull
          ## Init the target folder.
          # We will put all site documentation there.
          mkdir -p gh-pages
          sphinx-apidoc --separate --module-first -d 2 -H "API reference" --follow-links -o docs/apidocs pyphetools
          cd docs
          make html
          mv _build/html/* ../gh-pages
          
          function build_docs {
            # The function will checkout a branch and build the Javadoc & documentation 
            # into provided documentation directory.
            BRANCH=${1}
            DOCDIR=${2}
          
            git checkout ${BRANCH}
            git fetch
            git pull
            ## Init the target folder.
            # We will put all site documentation there.
            mkdir -p gh-pages/${DOCDIR}
          
            ## Build the docs
            # Generate the HTML pages and move the generated content into the target folder.
            printf "Building the %s documentation\n" ${DOCDIR}
  
            sphinx-apidoc --separate --module-first -d 2 -H "API reference" --follow-links -o docs/apidocs pyphetools
            cd docs
            make html
            
            mv _build/html/* ../gh-pages/${DOCDIR}
          }
                  
          # We store the docs for `main` in `stable` dir
          # TODO - enable when the docs make it into `main
          # build_docs main stable
          # We store the docs for `development` in `latest` dir
          build_docs develop latest
  
    - name: Deploy documentation.
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@v4.3.0
      with:
        branch: gh-pages
        clean: true
        folder: gh-pages
